import { configureStore, combineReducers } from '@reduxjs/toolkit';
import { persistStore, persistReducer, FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER } from 'redux-persist';
import storage from 'redux-persist/lib/storage'; // defaults to localStorage for web
import uiReducer from '../features/ui/uiSlice';
import curriculumReducer from '../features/curriculum/curriculumSlice';

const rootReducer = combineReducers({
  ui: uiReducer,
  curriculum: curriculumReducer,
});

const persistConfig = {
  key: 'root',
  storage,
  whitelist: ['ui', 'curriculum'], // Persist UI and Curriculum data
};

const persistedReducer = persistReducer(persistConfig, rootReducer);

export const store = configureStore({
  reducer: persistedReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: {
        // These actions are generated by redux-persist and contain non-serializable data, so we ignore them in checks
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
      },
    }),
});

export const persistor = persistStore(store);

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;